services:
  db:
    image: postgres:14.6-alpine
    container_name: db
    networks: 
      - net
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    volumes:
      - .:/docker-entrypoint-initdb.d
      - data_db:/var/lib/postgresql/data
    
      

  bot:
    build: ./bot
    container_name: bot
    networks: 
      - net
    restart: unless-stopped
    volumes:
      - .data:/app  
    

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    networks: 
      - net
    ports:
      - 8000:8000
    container_name: api
    depends_on:
      - db
    volumes:
      - .data:/app  


volumes:
  data_db:

networks:
  net:
    driver: bridge